### ISSUE TITLE
combination of chunked -> filter -> imap = bogus results

### ISSUE THREAD

**Issue by miguel-negrao** [ryanhaining/cppitertools#57] opened 2019-06-03 18:05 UTC
Hi 

The following code is a minimal reproducer of an issue I'm getting.

```
vector<int16_t> v(10000, 0);
  auto a = iter::chunked(v,480);
  auto b = iter::filter([](auto & chunk){ return true;}, a);
  auto c = iter::imap([](auto & chunk){ cout << chunk.size() << " "; return 1;}, b);
  for(auto &&x: c);
```
prints 

`18446738293966284791 480 480 480 480 480 480 480 480 480 480 480 480 480 480 480 480 480 480 480 400`

The first chunk size is always bogus.  Inside the first chunk there are also bogus values.

 Is this a bug, or I'm I doing something wrong ?

**Comment by ryanhaining** [comment] 2019-06-03 20:33
Nothing looks obviously wrong to me at a glance with your code. I will have to dig into this a bit and get back to you. Thanks for the report.

**Comment by ryanhaining** [comment] 2019-06-03 21:54
Looks like somethings going wrong inside `iter::filter`

With this setup

```c++
std::vector<int16_t> v(10000, 0);
auto chunks = iter::chunked(v,480);
auto filtered = iter::filter([](auto&){ return true;}, chunks);
```

Both of the following work fine when I use `chunks`

```c++
for(auto&& [chunk]: iter::zip(chunks)) {
  std::cout <<  chunk.size() << ' ';
}
```
and
```c++
for(auto&& [i, chunk]: iter::enumerate(chunks)) {
  std::cout <<  chunk.size() << ' ';
}
```

but replace `chunks` with `filtered` in either of the above and the problem appears.

The code produces the same error when using `iter::filter` with `iter::sliding_window`
```c++
std::vector<int16_t> v(10, 0);
auto sw = iter::sliding_window(v, 7);
auto filtered = iter::filter([](auto&) {return true; }, sw);
for(auto&& [w]: iter::zip(filtered)) { // iter::zip(sw) is fine
  std::cout <<  w.size() << ' ';
}
```

valgrind with clang is a lot uglier than with gcc, but both complain of "Invalid read of size 8" unsurprisingly.

**Comment by miguel-negrao** [comment] 2019-06-04 09:35
Looks like an issue somewhere then. Thanks for looking into this.

**Comment by ryanhaining** [comment] 2019-06-07 03:45
I believe I know where the problem is. `chunked` and `sliding_window` iterators both hold a `std::vector` value, which they return a reference to when dereferenced. The `filter` (etc) iterators hold `chunked` and `sliding_window` iterators by value as well.

At the time of construction, `filter` iterators find the first element and store a reference to it. During creation of anything that wraps filter (could be imap, zip, enumerate, whatever) I get a filter iterator and then move it. But the newly constructed object will still have a reference to the moved-from filter iterator's chunk iterator's vector.

Obvious fix to me seems to be to make chunked iterators hold a std::shared_ptr<vector<...>>, just gotta think this through to make sure that's right.

Thanks again for reporting this, I've got a bunch of test cases to add to the suite.

**Comment by ryanhaining** [comment] 2019-06-08 17:38
There may still be a way to surface the issue, but I'm unable to imagine any in the remaining tools. Please of course reopen if you see this again.

**Comment by ryanhaining** [comment] 2019-06-12 05:30
#59 is a duplicate of this. I need to address the issue in filter. It wasn't really an issue with chunked or sliding_window, which I suspected but wasn't sure. I'll add a few more commits that should fix the problem for real.

**Comment by ryanhaining** [comment] 2019-06-12 06:32
I believe these last few commits are the right fixes, does this work for you?

**Comment by miguel-negrao** [comment] 2019-06-12 10:01
The example in #57 now runs fine, thanks !

**Comment by ryanhaining** [comment] 2019-06-12 15:12
What a relief. Sorry this has been such a rough experience for you. I
definitely appreciate the bug reports

**Comment by miguel-negrao** [comment] 2019-06-13 17:43
Hum, I'm still having issues. In the following code I get a segmentation fault:

```
  std::vector<int> v{true, true, true, false, false, true, true};
  auto id = [](bool x) { return x; };
  auto a = iter::groupby(v, id);
  auto b = iter::filter([](auto &g){ return g.first; }, a);
  auto c = iter::imap([](auto &g) { return std::distance(g.second.begin(), g.second.end()); }, b);
  std::cout << "max size:" << *std::max_element(c.begin(), c.end()) << std::endl; 

Program received signal SIGSEGV, Segmentation fault.
0x00007fffffffc57c in ?? ()
-exec bt
#0  0x00007fffffffc57c in ?? ()
#1  0x00007fffffffd1b0 in ?? ()
```
I can't get much help from the debugger, the backtrace is useless even when the executable is compiled with debug symbols...

This only seems to happen with the use of std::max_element. If I just print c then it is okay...

```
  std::vector<int> v{true, true, true, false, false, true, true};
  auto id = [](bool x) { return x; };
  auto a = iter::groupby(v, id);
  auto b = iter::filter([](auto &g){ return g.first; }, a);
  auto c = iter::imap([](auto &g) { return std::distance(g.second.begin(), g.second.end()); }, b);
  for (auto x : c)
    std::cout << x << std::endl;
```

**Comment by ryanhaining** [comment] 2019-06-13 18:24
Oh right, max_element needs ForwardIterator and imap returns InputIterator.
I messed up previously putting max_element in the workaround. The group
element would have gone out of scope and imap doesn't save its result for
future iterators, meaning on the next access the underlying "group" has
gone away.

**Comment by miguel-negrao** [comment] 2019-06-13 18:30
Do you mean max_element can't be used with imap ? Or is it an implementation problem in imap ? What should I do to get the max element in this case ? thanks

**Comment by ryanhaining** [comment] 2019-06-13 18:51
max_element can't be used with imap. with upcoming c++20 ranges I have a
lot of work to do, but making this library ranges compatible should yield a
solution like imap(...) | max eventually, though I know that's not very
satisfying at the moment :/
I don't have any better solution than a naive implementation for getting
the max yourself unfortunately.

**Comment by miguel-negrao** [comment] 2019-06-13 20:23
Ok, got it. It's a pity that gcc can't detect the issue with the iterator type at compile time. Maybe in the future it will be possible with concepts ?

I can get the same result with std::accumulate which only needs InputIterator:

    std::accumulate(c.begin(), c.end(), 0, [](auto s, auto x){ return x>s ? x : s; });

**Comment by ryanhaining** [comment] 2019-06-13 20:41
Ah of course, std::accumulate!
libstdc++ doesn't check, but libc++ has a lot of checks for this type of
thing, if you run through clang + libc++ you should see errors. Here's a
live example: https://wandbox.org/permlink/YPlYH8APf4wLOMct

**Closed** 2019-08-05 15:10 UTC
Labels: bug
