### ISSUE TITLE
Feature request: Something like list comprehension

### ISSUE THREAD

**Issue by adamsd5** [ryanhaining/cppitertools#30] opened 2016-10-06 03:30 UTC
First, I love this library.  As soon as I first read of range-based for loops, I wanted this.  Now, the feature request...

It would be great to have a way to transform all of the elements in an iterator, as is often done with list comprehensions in python.

`for (auto&& p : transform([](int x) { return x*x; }, range(10))) { /* ... */ }`

or

`for (auto&& p : range(10) | transform([](int x) { return x*x; })) { /* ... */ }`

If there is some magic in C++ to do this already, perhaps that can go as an example in the readme.

**Comment by ryanhaining** [comment] 2016-10-06 04:32
iter::imap?

**Comment by ryanhaining** [comment] 2016-10-06 16:59
I think [`iter::imap`](https://github.com/ryanhaining/cppitertools#imap) is what you're looking for. As  runnable example:

```c++
#include <cppitertools/imap.hpp>
#include <cppitertools/range.hpp>
#include <iostream>

int main() {
  for (auto&& p : iter::imap([](int x) { return x*x; }, iter::range(10))) {
    std::cout << p << '\n';
  }
}
```

is that right?  A list comprehension of course is more involved and produces a list instead of the above which is roughly a generator. I've toyed with adding something like `to<std::vector>` or `to_vector` to actually generate a list, but the only nice way to get a list comprehension is language support

**Comment by NoSeatbelts** [comment] 2016-10-06 23:21
How unsatisfying is it to do something like the below?
```c++
int main() {
    std::vector<int> ret;
    for(auto &&p: iter:;imap([ret&](int x)-> void{return x*x;}, iter::range(10)))
        ret.push_back(p);
}
```

**Comment by ryanhaining** [comment] 2016-10-07 01:53
`[ret&](int x)-> void{return x*x;}`
I don't understand. Did you mean`[&ret](int x) { ret.push_back(x*x); `?

**Comment by NoSeatbelts** [comment] 2016-10-07 02:53
Sorry, I spliced together two versions I was toying with.
It should be 
```c++
int main() {
    std::vector<int> ret;
    for(auto &&p: iter::imap([ret&](int x){return x*x;}, iter::range(10)))
        ret.push_back(p);
    for(auto i: ret) puts(std::to_string(i).data());
}
```
or
```c++
int main() {
    std::vector<int> ret;
    for(auto &&p: iter::imap([ret&](int x)-> void{ret.push_back(x);}, iter::range(10)));
    for(auto i: ret) puts(std::to_string(i).data());
}
```

**Comment by ryanhaining** [comment] 2016-10-07 05:22
In the first example I don't think you need to be capturing the `ret` in the lambda. I'm not sure why you're jumping through so many hoops to print out an int like that when you could `std::cout` or at least `std::printf` it.

I feel like the right way to do this, assuming you need an intermediate vector would be to use the vector constructor that takes a pair of iterators, rather than repeated `push_back` calls:

```c++
int main() {
    auto sqs = iter::imap([](int x){return x*x;}, iter::range(10));
    std::vector<int> ret(std::begin(sqs), std::end(sqs));
    for(auto i: ret) {
      std::cout << i << '\n';
    }
}
```

As for doing this with a conversion to `std::vector` specifically, this is a first draft:

```c++
template <typename Seq>
std::vector<std::remove_reference_t<decltype(*std::begin(std::declval<Seq&>()))>>
to_vector(Seq&& seq) {
  return {std::begin(seq), std::end(seq)};
}

int main() {
    auto ret = to_vector(iter::imap([](int x){return x*x;}, iter::range(10)));
    for(auto i: ret) {
      std::cout << i << '\n';
    }
}

```

**Comment by ryanhaining** [comment] 2016-10-08 16:20
@adamsd5, is `imap` + `vector` constructor good enough for your purposes?

**Comment by ryanhaining** [comment] 2016-10-13 00:28
I'm gonna go ahead and close this, please reopen if you wanna discuss this further

**Closed by ryanhaining** 2016-10-13 00:28 UTC

**Comment by NikolausDemmel** [comment] 2019-01-18 20:42
@ryanhaining, is something like `to_vector` part of this library? In particular I'm looking for the same for other containers as well, like `set`. Of course I can easily add it myself, but I was woundering if cppitertools has such container constructors?

**Comment by ryanhaining** [comment] 2019-01-20 20:31
Though I definitely see the utility and end up writing vector constructors myself, I haven't come up with an intuitive way to deduce things that would be safe in the majority of cases. Consider this:

```cpp
std::string get_str() { return {}; }

int main() {
  auto v = iter::to_vector(
      iter::enumerate(get_str())
  );
}
```

`enumerate` itself is fine handling a temporary, the `std::string` returned from `get_str` will be moved into the Enumerable object that `enumerate returns, so a line like `for (auto&& [i, c] : iter::enumerate(get_str())` works just fine.

The problem is that the type that enumerate returns will use the underlying iterable's `reference` type (effectively), so what you end up with is enumerate yielding a subclass of `std::pair<std::size_t, char&>`. Again, this is fine for normal use, but if you put those into a vector, now you have a `std::vector<std::pair<std::size_t, char&>>`, but all of those references are dangling since the `vector` won't extend the lifetime of the Enumerable.

I'd have to be pretty creative about this to remove all the references, but who even knows when keeping the reference might be the right thing to do? Of course, if I required the caller to specify `iter::to_vector<std::pair<std::size_t, char>>` it could work, alternatively allow any container with `iter::to<std::vector<std::pair<std::size_t, char>>>` but I don't even know if it's still useful at that point.

**Comment by NikolausDemmel** [comment] 2019-01-20 21:03
Hm... thanks for the explanation, I see roughly what the issue is.

In the example above `to_vector(iter::imap([](int x){return x*x;}, iter::range(10)))` it is pretty clear that we expect `vector<int>` but for example in the following I can see both `vector<string>` and `vector<string&>` being useful in specific situations:

```cxx
struct Foo {
 std::string& name();
}

std::vector<Foo> foo = { ... };

auto names = iter::to_vector(iter::imap([](auto& x){return x.name();}, foo));
```

However, I think as a default, it should be vector of non-references (maybe with variant `iter::refs_to<std::vector>(...)`). But that of course leaves the issue highlighted with `enumerate`. Not sure if it makes sense or could even be implemented, but intuitively it should ignore all the "levels of nesting" that were added by intermediate range expressions and make sure it makes a "deep copy" up until the "original input". I.e. in your example it should somehow detect that it needs to copy at least until the level of elements of what was returned by `get_str()` (but no further), no matter how many levels were added by `enumerate` or similar. When you say `enumerate` returns subclasses of `std::pair`, that sounds like something you could use in template specialization, however, I have no clue if such reasoning always help, e.g. when mixing with other (custom) range utilities...

**Comment by NikolausDemmel** [comment] 2019-01-20 21:08
PS: In your example, the compiler doesn't happen to be not smart enough to detect that we store references to a temporary? I was thinking that a simple implementation, i.e. a generatlization of your proposal above ideally to all containers (maybe with template templates, if that can be implemented, i.e. `iter::to<std::vector>(...)` or `iter::as<std::vector>(...)` or `iter::copy_to<std::vector>(...)`, ...), that only removes references "one level deep" would already be helpful in many situations. Question is if potentially harmful situations could be detected by the compiler to warn the user.

```
template <typename Seq>
std::vector<std::decay_t<decltype(*std::begin(std::declval<Seq&>()))>>
to_vector(Seq&& seq) {
  return {std::begin(seq), std::end(seq)};
}
```

**Comment by ryanhaining** [comment] 2019-01-21 17:43
In your first example I would always do `vector<string>` and that wouldn't be too hard, as you've already demonstrated.

I believe that even in cases where it's not an rvalue, if you can't remove all the references then it won't be intuitively safe

```cpp
auto get_vector() {
  std::string s{"test string"};
  auto e = iter::enumerate(s);
  return iter::to_vector(e); // full of references to local variable `s`
}

int main() {
  auto v = get_vector(); 
  v[0].second = 'b'; // dangling reference
}
```

Some of the itertools would work fine with this, removing all the nesting is certainly possible as long as I know all the types that could be contained, but safety is my top concern with this.
